title: "Build a CI/CD pipelines by using OCI DevOps services."
stackDescription: "Install ArgoCd on an existing or new OKE cluster" 
description: "Install ArgoCd on an existing or new OKE cluster"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

#################
# Variable Groups
#################
variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - compartment_ocid
  - region
  - oke_compartment_description
  - user_ocid
  - fingerprint
  - private_key_path
  - network_cidrs






- title: OKE Cluster Configuration
  visible: true 
  variables:
    - create_new_oke_cluster
    - existent_oke_cluster_id
    - create_new_compartment_for_oke
    - oke_compartment_description
    - cluster_options_add_ons_is_kubernetes_dashboard_enabled
    - cluster_options_admission_controller_options_is_pod_security_policy_enabled
    - cluster_workers_visibility
    - cluster_endpoint_visibility
    - k8s_version

- title: OKE Worker Nodes Configuration
  visible: true 
  variables:
    - generate_public_ssh_key
    - public_ssh_key
    - num_pool_workers
    - node_pool_name
    - node_pool_shape
    - node_pool_node_shape_config_ocpus
    - node_pool_node_shape_config_memory_in_gbs
    - image_operating_system
    - image_operating_system_version
    #- create_dynamic_group_for_nodes_in_compartment
    #- existent_dynamic_group_for_nodes_in_compartment
    #- create_compartment_policies
    #- create_tenancy_policies

#################
# Output Groups
#################


######################
# Variable Definitions
######################

variables:

# Required
  
  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_id: 
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create resources"
    required: true

  app_name:
    type: string
    title: "Project Name"
    required: true

  project_logging_config_retention_period_in_days:
    type: string
    title: "Project Logs retention period"
    description: "Days to retain logs from the Project."
    default: 30
    required: true
    visible: 
      and:
        - show_advanced

  create_new_oke_cluster:
    type: boolean
    title: "Create new OKE cluster?"
    required: false
  
  existent_oke_cluster_id:
    type: string
    required: false
    visible: 
      not:
        - create_new_oke_cluster     
    title: "Use existing OKE cluster OCID"

  create_new_compartment_for_oke:
    type: boolean
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "Create new compartment for OKE"

  oke_compartment_description:
    type: string
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "OKE new compartment description"

  cluster_options_add_ons_is_kubernetes_dashboard_enabled:
    type: boolean
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "OKE Cluster Add-ons: Enabled Kubernetes Dashboard?"

  cluster_options_admission_controller_options_is_pod_security_policy_enabled:
    type: boolean
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "OKE Cluster Add-ons: Admission Controler options - Enabled POD Security Policy?"

  cluster_workers_visibility:
    type: enum
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "Choose OKE Worker Nodes visibility type"
    enum:
      - "Private"
      - "Public"

  cluster_endpoint_visibility:
    type: enum
    required: false
    visible: 
      and:
        - create_new_oke_cluster     
    title: "Choose OKE API Endpoint visibility type"
    enum:
      - "Private"
      - "Public"

  
  
  k8s_version:
    type: enum
    enum: # Necessary hardcoded supported versions, as ORM does not retrieve the versions from OKE.
      - "Latest"
      - "v1.19.7"
      - "v1.18.10"
      - "v1.17.13"
      - "v1.16.15"
    title: "Kubernetes Version"
    required: false
    default: "Latest"
    visible:
      and:
        - create_new_oke_cluster
        - show_advanced

  generate_public_ssh_key:
    type: boolean
    title: "Auto generate public ssh key?"
    required: true
    visible:
      and:
        - create_new_oke_cluster
        - show_advanced

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: "Import your own SSH public key"
    additionalProps:
      allowMultiple: true
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible:
      and:
        - and:
          - create_new_oke_cluster
          - show_advanced
        - not:
          - generate_public_ssh_key

  num_pool_workers:
    type: integer
    title: "Number of Worker Nodes"
    minimum: 1
    maximum: 1000
    required: true
    visible:
      and:
        - create_new_oke_cluster

  node_pool_name:
    type: string
    title: "Node Pool Name"
    required: false
    visible:
      and:
        - create_new_oke_cluster
        - show_advanced

  node_pool_shape:
    type: oci:core:instanceshape:name
    title: "Select a shape for the Worker Nodes instances"
    required: false
    dependsOn:
      compartmentId: compartment_ocid
    visible:
      and:
        - create_new_oke_cluster

  node_pool_node_shape_config_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: "Number of OCPUs"
    visible:
      and:
        - and:
          - create_new_oke_cluster
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"

  node_pool_node_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: "Amount of memory (GB)"
    visible:
      and:
        - and:
          - create_new_oke_cluster
        - or:
          - eq:
            - node_pool_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - node_pool_shape 
            - "VM.Standard.A1.Flex"

  image_operating_system:
    type: enum
    title: "Image OS"
    enum:
      - "Oracle Linux"
    required: false
    visible:
      and:
        - create_new_oke_cluster
        - show_advanced

  image_operating_system_version:
    type: string
    required: false
    title: "Image OS Version"
    visible:
      and:
        - create_new_oke_cluster
        - show_advanced

  

  
  project_description:
    type: string
    title: "Project Description"
    description: "A short description for the project"
    default: "Project for OKE deployment"
    required: false
    visible: 
      and:
        - show_advanced
  
 

  
  


  
  
  

